include(CheckCXXCompilerFlag)
macro(COMPILE_OPTION target opt)
    string(TOUPPER "HAVE_CXX_FLAG_${opt}" SANITIZED_FLAG)
    string(REPLACE "+" "X" SANITIZED_FLAG ${SANITIZED_FLAG})
    string(REGEX REPLACE "[^A-Za-z_0-9]" "_" SANITIZED_FLAG ${SANITIZED_FLAG})
    string(REGEX REPLACE "_+" "_" SANITIZED_FLAG ${SANITIZED_FLAG})
    CHECK_CXX_COMPILER_FLAG(${opt} ${SANITIZED_FLAG})
    if(${SANITIZED_FLAG})
        target_compile_options(${target} PRIVATE ${opt})
    elseif(${ARGV2})
        message(FATAL_ERROR "Compiler support for option ${opt} is required")
    endif(${SANITIZED_FLAG})
endmacro(COMPILE_OPTION)